In [147]:
import pandas as pd 
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [148]:
tips= sns.load_dataset("tips")
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [149]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [150]:
y= tips["tip"]
x= pd.get_dummies(tips.drop("tip", axis= "columns"), columns= ["sex", "smoker", "day", "time"])

In [151]:
x

total_bill  size  sex_Male  sex_Female  smoker_Yes  smoker_No  day_Thur  \
0         16.99     2     False        True       False       True     False   
1         10.34     3      True       False       False       True     False   
2         21.01     3      True       False       False       True     False   
3         23.68     2      True       False       False       True     False   
4         24.59     4     False        True       False       True     False   
..          ...   ...       ...         ...         ...        ...       ...   
239       29.03     3      True       False       False       True     False   
240       27.18     2     False        True        True      False     False   
241       22.67     2      True       False        True      False     False   
242       17.82     2      True       False       False       True     False   
243       18.78     2     False        True       False       True      True   

     day_Fri  day_Sat  day_Sun  time_Lunch  time_Dinner  
0      False    False     True       False         True  
1      False    False     True       False         True  
2      False    False     True       False         True  
3      False    False     True       False         True  
4      False    False     True       False         True  
..       ...      ...      ...         ...          ...  
239    False     True    False       False         True  
240    False     True    False       False         True  
241    False     True    False       False         True  
242    False     True    False       False         True  
243    False    False    False       False         True  

[244 rows x 12 columns]

In [152]:
y

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [153]:
X_train, X_test, y_train, y_test= train_test_split(x, y, test_size= 0.3, random_state= 42)

In [154]:
print(f"{X_train.shape= }")
print(f"{y_train.shape= }")
print(f"{X_test.shape= }")
print(f"{y_test.shape= }")

X_train.shape= (170, 12)
y_train.shape= (170,)
X_test.shape= (74, 12)
y_test.shape= (74,)


In [155]:
scaler= MinMaxScaler()

scaler.fit(X_train)

MinMaxScaler()

In [156]:
scaled_X_train= scaler.transform(X_train)
scaled_X_test= scaler.transform(X_test)

In [157]:
print(f"{scaled_X_train.shape= }")
print(f"{scaled_X_train.min()= }")
print(f"{scaled_X_train.max()= }")

print(f"{scaled_X_test.shape= }")
print(f"{scaled_X_test.min()= }")
print(f"{scaled_X_test.max()= }")

scaled_X_train.shape= (170, 12)
scaled_X_train.min()= 0.0
scaled_X_train.max()= 1.0000000000000002
scaled_X_test.shape= (74, 12)
scaled_X_test.min()= -0.05947625388371061
scaled_X_test.max()= 1.0000000000000002


In [158]:
model= LinearRegression()
model.fit(scaled_X_train, y_train)

LinearRegression()

In [159]:
print(f"{model.coef_= }")
print(f"{model.intercept_= }")

model.coef_= array([ 4.34348068,  1.36405957,  0.03588579, -0.03588579, -0.15079726,
        0.15079726, -0.10414714,  0.14790837,  0.00650135, -0.05026258,
        0.09205583, -0.09205583])
model.intercept_= 1.2760521215887528


In [160]:
test_sample_features= scaled_X_test[0]
test_sample_labels= y_test.values[0]

print(f"{test_sample_labels= }")
print(f"{test_sample_features= }")


test_sample_labels= 3.18
test_sample_features= array([0.31225033, 0.2       , 1.        , 0.        , 0.        ,
       1.        , 0.        , 0.        , 1.        , 0.        ,
       0.        , 1.        ])


In [161]:
model.predict(test_sample_features.reshape(1, -1))

array([3.0062459])

In [162]:
y_pred= model.predict(scaled_X_test)
y_pred

array([3.0062459 , 1.88433635, 3.95104596, 3.83538235, 2.04894087,
       2.46184844, 3.60902453, 2.30041089, 2.4636599 , 2.3463007 ,
       2.80200027, 2.13388682, 2.12401121, 2.1331474 , 1.7952912 ,
       3.16700534, 2.94392994, 3.11913412, 2.609629  , 5.95806896,
       3.56396028, 3.35906423, 2.10175288, 2.01628703, 2.9530325 ,
       2.2960318 , 2.02892625, 3.15918704, 3.17411621, 6.77347879,
       4.98147104, 1.5402207 , 3.35811926, 2.74995622, 2.87580148,
       3.96419663, 2.09515484, 5.49696602, 2.36595831, 2.9793722 ,
       2.10882457, 2.49705316, 3.34758617, 2.23575017, 1.86430637,
       0.74548063, 1.74316992, 3.17013342, 1.8979276 , 2.37583392,
       3.13360143, 3.56515218, 4.64122176, 2.70955892, 2.91767219,
       2.42519878, 1.43622406, 2.81345936, 2.97552712, 2.5793591 ,
       4.66297061, 2.63576328, 2.98622782, 2.61620236, 3.04576714,
       3.04050691, 2.24099976, 1.44999901, 3.63004572, 3.67534225,
       3.49028613, 4.32604305, 2.8358341 , 2.91808746])

In [169]:
y_test.to_numpy()

array([3.18, 2.  , 2.  , 5.16, 2.  , 2.  , 2.56, 2.52, 3.23, 3.  , 3.  ,
       1.47, 1.5 , 2.  , 1.83, 1.36, 4.  , 3.92, 2.47, 5.  , 2.45, 3.35,
       4.  , 1.45, 3.5 , 2.31, 1.71, 5.  , 2.  , 5.  , 4.  , 1.44, 2.34,
       3.21, 3.5 , 2.92, 1.5 , 5.  , 2.75, 2.  , 1.25, 2.  , 2.55, 1.67,
       2.  , 1.  , 1.61, 2.31, 1.44, 2.72, 2.03, 4.  , 4.5 , 2.03, 3.51,
       2.  , 5.15, 1.75, 2.74, 3.  , 5.14, 3.5 , 5.65, 2.5 , 2.01, 4.08,
       2.09, 1.  , 3.41, 3.48, 2.  , 3.  , 2.71, 3.  ])

In [164]:
mean_absolute_error(y_test, y_pred)

0.7171821289867385

In [165]:
mean_squared_error(y_test, y_pred)

0.9318323215910997

In [166]:
ramse= np.sqrt(mean_squared_error(y_test, y_pred))

0.9653146231105689